---
- name: Build environment
  hosts: build
  become: yes

  tasks:
  - name: apt update
    apt:
      update_cache: yes

  - name: Ensure default-jdk packedge is present
    apt:
      name: default-jdk
      state: present

  - name: Ensure git packedge is present
    apt:
      name: git
      state: present

  - name: Ensure maven packedge is present
    apt:
      name: maven
      state: present

  - name: Clone Boxfuse repo
    git:
      repo: 'https://github.com/boxfuse/boxfuse-sample-java-war-hello.git'
      dest: /tmp/boxfuse
      version: master
      clone: yes

  - name: Maven package & push app into app repo
    command: cd /tmp/boxfuse/ && mvn package && cd /tmp/boxfuse/target/ && git init && git add . && git remote add origin https://github.com/jk84reg/test-dz/tree/master/DZ-8.git && git push -u origin master

- name: PROD
  hosts: prod-app
  become: yes

  tasks:
  - name: apt update
    apt:
      update_cache: yes
  - name: Ensure default-jdk packedge is present
    apt:
      name: default-jdk
      state: present

  - name: Ensure git packedge is present
    apt:
      name: git
      state: present

  - name: Ensure tomcat9 packedge is present
    apt:
      name: tomcat9
      state: present

  - name: Get sparkjava-hello-world-1.0.war
    git:
      repo: https://github.com/jk84reg/test-dz/tree/master/DZ-8.git
      dest: /var/lib/tomcat9/webapps/
      version: master
      clone: yes